name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"

permissions:
  id-token: write
  contents: read
  pull-requests: read

env:
  GO_VERSION: "1.21.3" # https://go.dev/dl/
  GOLANGCI_LINT_VERSION: "v1.55.1" # https://github.com/golangci/golangci-lint/releases

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint go code
        uses: golangci/golangci-lint-action@v3
        working-directory: ./ios/server
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          skip-cache: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build go code
        working-directory: ./ios/server
        run: go build
