name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"

env:
  GO_VERSION: "1.22.5" # https://go.dev/dl/
  GOLANGCI_LINT_VERSION: "v1.59.1" # https://github.com/golangci/golangci-lint/releases

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cwd: ["./ios/server", "./ai"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint go code
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          skip-cache: true
          working-directory: ${{ matrix.cwd }}

  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cwd: ["./ios/server", "./ai"]
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ env.GO_VERSION }}
          work-dir: ${{ matrix.cwd }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cwd: ["./ios/server", "./ai"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build go code
        working-directory: ${{ matrix.cwd }}
        run: go build
